[general]
import = [
    "~/.config/alacritty/themes/borg.toml"
]

[font]
size = 9

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[window]
opacity = 0.8
